import type { AppLocale } from "./i18n";
import type { SupporterCopy } from "./supporterLocale";

// Shared by app and local website; normal released and safety features stay free.
type PlanCopy = Pick<SupporterCopy, "freeTitle" | "freeFeatures" | "candidateTitle" | "candidateKicker" | "candidateFeatures" | "monthlyPrice" | "pendingBody">;
export const planCopies: Record<AppLocale, PlanCopy> = {
  ja: { freeTitle:"Free Plan", freeFeatures:["サーバー登録は3個まで", "通常公開された機能・標準テーマ", "一括操作・保存・安全停止・既存バックアップ／復元"], candidateTitle:"Supporter", candidateKicker:"月額500円・受付準備中", candidateFeatures:["サーバー登録数が無制限（PC性能の上限は別）", "提供中の先行体験を任意で利用（現在は対象なし）", "標準＋新しい限定テーマ3種類", "Discord運営通知（起動完了・停止・異常終了）"], monthlyPrice:"{amount} / 月", pendingBody:"月額500円。本番受付は準備中です。先行体験の対象は現在ありません。登録数を超えても既存サーバー・ワールド・無料機能は維持されます。" },
  en: { freeTitle:"Free Plan", freeFeatures:["Up to 3 registered servers", "Public features and standard themes", "Batch operations, saving, safe stop, existing backup/restore"], candidateTitle:"Supporter", candidateKicker:"JPY 500/month · signup preparing", candidateFeatures:["Unlimited registered servers (PC capacity still applies)", "Opt-in ready previews (none currently available)", "Standard + 3 new exclusive themes", "Discord operations alerts: ready, stopped, crashed"], monthlyPrice:"{amount} / month", pendingBody:"JPY 500/month. Public signup is not enabled. No previews are currently available. Existing servers, worlds and free features remain accessible after expiry." },
  de: { freeTitle:"Free Plan", freeFeatures:["Bis zu 3 registrierte Server", "Öffentliche Funktionen und Standardthemen", "Stapelaktionen, Speichern, sicheres Stoppen, bestehende Sicherung/Wiederherstellung"], candidateTitle:"Supporter", candidateKicker:"500 JPY/Monat · Anmeldung in Vorbereitung", candidateFeatures:["Unbegrenzte registrierte Server (PC-Leistung bleibt begrenzt)", "Freiwillige Vorschau (derzeit keine verfügbar)", "Standardthemen + 3 neue exklusive Themen", "Discord-Meldungen: bereit, gestoppt, abgestürzt"], monthlyPrice:"{amount} / Monat", pendingBody:"500 JPY/Monat. Die Anmeldung ist noch nicht freigeschaltet. Aktuell keine Vorschau. Bestehende Server, Welten und kostenlose Funktionen bleiben nach Ablauf zugänglich." },
  es: { freeTitle:"Free Plan", freeFeatures:["Hasta 3 servidores registrados", "Funciones públicas y temas estándar", "Operaciones por lotes, guardado, parada segura y copias/restauración existentes"], candidateTitle:"Supporter", candidateKicker:"500 JPY/mes · registro en preparación", candidateFeatures:["Servidores registrados ilimitados (según capacidad del PC)", "Acceso anticipado opcional (sin funciones disponibles ahora)", "Temas estándar + 3 nuevos temas exclusivos", "Alertas Discord: listo, detenido, fallo"], monthlyPrice:"{amount} / mes", pendingBody:"500 JPY/mes. El registro aún no está habilitado. No hay acceso anticipado disponible. Los servidores, mundos y funciones gratuitas existentes se conservan al vencer." },
  fr: { freeTitle:"Free Plan", freeFeatures:["Jusqu’à 3 serveurs enregistrés", "Fonctions publiques et thèmes standards", "Actions groupées, sauvegarde, arrêt sûr et restauration existante"], candidateTitle:"Supporter", candidateKicker:"500 JPY/mois · inscription en préparation", candidateFeatures:["Serveurs enregistrés illimités (capacité du PC distincte)", "Aperçus facultatifs prêts (aucun actuellement)", "Thèmes standards + 3 nouveaux thèmes exclusifs", "Alertes Discord : prêt, arrêté, incident"], monthlyPrice:"{amount} / mois", pendingBody:"500 JPY/mois. L’inscription n’est pas activée. Aucun aperçu disponible. Les serveurs, mondes et fonctions gratuites existants restent accessibles après expiration." },
  ko: { freeTitle:"Free Plan", freeFeatures:["등록 서버 최대 3개", "공개 기능과 기본 테마", "일괄 작업·저장·안전 종료·기존 백업/복원"], candidateTitle:"Supporter", candidateKicker:"월 500엔 · 신청 준비 중", candidateFeatures:["등록 서버 수 무제한 (PC 성능 제한은 별도)", "준비된 기능 선택적 미리 체험 (현재 없음)", "기본 테마 + 새로운 전용 테마 3종", "Discord 운영 알림: 시작 완료·종료·비정상 종료"], monthlyPrice:"{amount} / 월", pendingBody:"월 500엔. 정식 신청은 준비 중입니다. 현재 선행 체험은 없습니다. 만료 후에도 기존 서버·월드·무료 기능을 유지합니다." },
  "pt-BR": { freeTitle:"Free Plan", freeFeatures:["Até 3 servidores registrados", "Recursos públicos e temas padrão", "Operações em lote, salvamento, parada segura e backup/restauração existentes"], candidateTitle:"Supporter", candidateKicker:"500 JPY/mês · inscrições em preparação", candidateFeatures:["Servidores registrados ilimitados (capacidade do PC é separada)", "Prévia opcional de recursos prontos (nenhum disponível agora)", "Temas padrão + 3 novos temas exclusivos", "Alertas Discord: pronto, parado, falha"], monthlyPrice:"{amount} / mês", pendingBody:"500 JPY/mês. Inscrições ainda não habilitadas. Nenhuma prévia disponível. Servidores, mundos e recursos gratuitos existentes continuam acessíveis após expirar." },
  "zh-CN": { freeTitle:"Free Plan", freeFeatures:["最多注册3个服务器", "公开功能与标准主题", "批量操作、保存、安全停止和现有备份/恢复"], candidateTitle:"Supporter", candidateKicker:"每月500日元 · 申请准备中", candidateFeatures:["服务器注册数无限制（不代表PC性能无限）", "自愿体验已就绪的新功能（目前无可用体验）", "标准主题＋3款全新专属主题", "Discord运营通知：启动完成、停止、异常退出"], monthlyPrice:"每月 {amount}", pendingBody:"每月500日元。尚未开放正式申请。目前没有先行体验。到期后保留现有服务器、世界和免费功能。" },
  "zh-TW": { freeTitle:"Free Plan", freeFeatures:["最多註冊3個伺服器", "公開功能與標準主題", "批次操作、儲存、安全停止與現有備份/還原"], candidateTitle:"Supporter", candidateKicker:"每月500日圓 · 申請準備中", candidateFeatures:["伺服器註冊數無限制（不代表PC效能無限）", "自願體驗已就緒的新功能（目前無可用體驗）", "標準主題＋3款全新專屬主題", "Discord營運通知：啟動完成、停止、異常結束"], monthlyPrice:"每月 {amount}", pendingBody:"每月500日圓。尚未開放正式申請。目前沒有先行體驗。到期後保留現有伺服器、世界與免費功能。" },
};
