import type { AppLocale } from "./i18n";

const en = {
  kicker: "SUPPORT", freePlan: "Free Plan", supporterPlan: "Supporter", registeredCount: "Registered servers: {count}", countChecking: "checking", unlimited: "unlimited", serverLimit: "up to {count}", paidUntil: "Paid through {date}", cancellation: "Cancellation scheduled; benefits remain available through the paid period", stateChecking: "Checking membership status", refresh: "Refresh membership status", freePrice: "¥0 / month", productionPending: "Enrollment is being prepared", unlimitedCaveat: "“Unlimited” refers to registered servers. It does not guarantee simultaneous operation beyond this PC’s capacity.", previewHeading: "Early access previews", previewOptIn: "Opt in to previews when they are ready", noPreviews: "There are no previews available right now. Monthly additions are not guaranteed.", previewItem: "In development: {audience} / {impact}", themeHeading: "Supporter themes", themeIntro: "Existing dark and light themes and accent colors remain free. Everyone can preview these themes.", themeApplied: "Applied", applyTheme: "Apply theme", supporterOnly: "Supporter only", resetTheme: "Restore standard theme", themeResetNote: "After qualification ends or you sign out, the app returns to the standard theme. Windows title bars are not affected.", saved: "Settings saved", failed: "Could not save the setting. Check your connection and try again.", refreshFailed: "Membership refresh failed. Existing servers remain available.",
  themeDescriptions: { midnight: "Deep blue and clear aqua", orchid: "Calm violet and soft lilac", ember: "Charcoal and warm amber" },
  states: { signed_out: "Not signed in", session_expired: "Your sign-in session has expired", not_configured: "Membership connection is being prepared", free: "Free plan", verified: "Membership verified", offline: "Using offline qualification (up to 24 hours and within the paid period)", unavailable: "Connection failed; no valid offline qualification is available", expired: "Membership qualification has expired", past_due: "Payment needs attention (free features remain available)", unpaid: "Payment incomplete (free features remain available)", canceled: "Subscription ended", invalid_qualification: "Membership signature could not be verified", clock_invalid: "Check this device’s clock", browser_demo: "Browser display demo", unknown: "Checking membership status" },
} as const;
type StateKey = keyof typeof en.states;
type PanelMessages = { [Key in Exclude<keyof typeof en, "themeDescriptions" | "states">]: string } & {
  themeDescriptions: Record<keyof typeof en.themeDescriptions, string>;
  states: Record<StateKey, string>;
};
const copies: Record<AppLocale, PanelMessages> = {
  en,
  ja: {
    kicker: "応援プラン", freePlan: "Freeプラン", supporterPlan: "Supporter", registeredCount: "登録数：{count}", countChecking: "確認中", unlimited: "無制限", serverLimit: "{count}個", paidUntil: "支払い済み期間：{date}まで", cancellation: "期間末の解約予約済み・支払い済み期間まで特典を利用できます", stateChecking: "会員資格を確認中", refresh: "会員状態を再確認", freePrice: "¥0 / 月", productionPending: "本番受付は準備中", unlimitedCaveat: "「無制限」は登録数です。PCの性能を超えた同時起動を保証しません。", previewHeading: "新機能の先行体験", previewOptIn: "提供準備が整った先行体験を任意で有効化", noPreviews: "現在提供中の先行体験はありません。毎月の追加はお約束しません。", previewItem: "開発中：{audience}／{impact}", themeHeading: "Supporter限定テーマ", themeIntro: "既存のダーク／ライト、アクセント色は引き続き無料です。見本はどなたでも確認できます。", themeApplied: "適用中", applyTheme: "適用する", supporterOnly: "Supporter限定", resetTheme: "標準テーマに戻す", themeResetNote: "資格終了・ログアウト後は標準テーマへ戻します。Windows標準タイトルバーは対象外です。", saved: "設定を保存しました", failed: "設定を保存できませんでした。通信状態を確認して再試行してください。", refreshFailed: "会員資格の再確認に失敗しました。既存サーバーは引き続き利用できます。",
    themeDescriptions: { midnight: "深い青と澄んだ水色", orchid: "落ち着いた紫と柔らかなライラック", ember: "墨色と温かな琥珀" },
    states: { signed_out: "ログインしていません", session_expired: "ログインの有効期限が切れています", not_configured: "会員資格の接続準備中", free: "Freeプラン", verified: "会員資格を確認済み", offline: "オフライン資格で利用中（最長24時間・契約期間内）", unavailable: "通信失敗・有効なオフライン資格がありません", expired: "会員資格の有効期限が切れています", past_due: "支払い確認が必要です（無料機能は利用できます）", unpaid: "支払い未完了（無料機能は利用できます）", canceled: "契約が終了しました", invalid_qualification: "会員資格の署名を確認できません", clock_invalid: "端末の時刻を確認してください", browser_demo: "ブラウザの表示デモです", unknown: "会員資格を確認中" },
  },
  "zh-CN": {
    kicker: "支持项目", freePlan: "免费版", supporterPlan: "支持者版", registeredCount: "服务器数量：{count}", countChecking: "正在确认", unlimited: "不限数量", serverLimit: "最多 {count} 个", paidUntil: "已付款至 {date}", cancellation: "已安排在周期结束时取消，付费期间内仍可使用权益", stateChecking: "正在确认会员资格", refresh: "重新确认会员状态", freePrice: "¥0 / 月", productionPending: "正式订阅正在准备中", unlimitedCaveat: "“不限数量”指可登记的服务器数量，不代表这台电脑可以同时运行任意数量的服务器。", previewHeading: "抢先体验", previewOptIn: "功能准备就绪后自愿参加抢先体验", noPreviews: "目前没有开放抢先体验；不保证每月都会新增内容。", previewItem: "开发中：{audience}／{impact}", themeHeading: "支持者专属主题", themeIntro: "现有深色、浅色主题和强调色仍免费提供。所有人都可以预览这些主题。", themeApplied: "已应用", applyTheme: "应用主题", supporterOnly: "支持者专属", resetTheme: "恢复标准主题", themeResetNote: "资格结束或退出登录后，应用会恢复标准主题。Windows 标题栏不受影响。", saved: "设置已保存", failed: "无法保存设置。请检查网络后重试。", refreshFailed: "会员状态更新失败，现有服务器仍可继续使用。",
    themeDescriptions: { midnight: "深蓝与清透的水蓝色", orchid: "沉静的紫色与柔和的丁香色", ember: "炭墨色与温暖的琥珀色" },
    states: { signed_out: "尚未登录", session_expired: "登录已过期", not_configured: "会员资格连接正在准备中", free: "免费版", verified: "会员资格已验证", offline: "正在使用离线资格（最长 24 小时且在付费期内）", unavailable: "连接失败，且没有有效的离线资格", expired: "会员资格已过期", past_due: "需要处理付款（免费功能仍可使用）", unpaid: "付款未完成（免费功能仍可使用）", canceled: "订阅已结束", invalid_qualification: "无法验证会员资格签名", clock_invalid: "请检查设备时间", browser_demo: "浏览器界面演示", unknown: "正在确认会员资格" },
  },
  "zh-TW": {
    kicker: "支持專案", freePlan: "免費版", supporterPlan: "支持者版", registeredCount: "伺服器數量：{count}", countChecking: "確認中", unlimited: "不限數量", serverLimit: "最多 {count} 個", paidUntil: "已付款至 {date}", cancellation: "已預約於週期結束時取消，付費期間仍可使用權益", stateChecking: "正在確認會員資格", refresh: "重新確認會員狀態", freePrice: "¥0 / 月", productionPending: "正式訂閱準備中", unlimitedCaveat: "「不限數量」指可登記的伺服器數量，不代表這台電腦能同時執行任意數量的伺服器。", previewHeading: "搶先體驗", previewOptIn: "功能準備就緒後自願參加搶先體驗", noPreviews: "目前沒有開放搶先體驗；不保證每月都會新增內容。", previewItem: "開發中：{audience}／{impact}", themeHeading: "支持者限定主題", themeIntro: "現有深色、淺色主題和強調色仍免費提供。所有人都可以預覽這些主題。", themeApplied: "已套用", applyTheme: "套用主題", supporterOnly: "支持者限定", resetTheme: "還原標準主題", themeResetNote: "資格結束或登出後，應用程式會還原標準主題。Windows 標題列不受影響。", saved: "設定已儲存", failed: "無法儲存設定。請檢查網路後再試一次。", refreshFailed: "會員狀態更新失敗，現有伺服器仍可繼續使用。",
    themeDescriptions: { midnight: "深藍與清透的水藍色", orchid: "沉靜的紫色與柔和的丁香色", ember: "炭墨色與溫暖的琥珀色" },
    states: { signed_out: "尚未登入", session_expired: "登入已逾期", not_configured: "會員資格連線準備中", free: "免費版", verified: "會員資格已驗證", offline: "使用離線資格中（最長 24 小時且仍在付費期間）", unavailable: "連線失敗，且沒有有效的離線資格", expired: "會員資格已逾期", past_due: "需要處理付款（免費功能仍可使用）", unpaid: "付款尚未完成（免費功能仍可使用）", canceled: "訂閱已結束", invalid_qualification: "無法驗證會員資格簽章", clock_invalid: "請檢查裝置時間", browser_demo: "瀏覽器介面示範", unknown: "正在確認會員資格" },
  },
  ko: {
    kicker: "후원", freePlan: "무료 플랜", supporterPlan: "서포터", registeredCount: "등록 서버 수: {count}", countChecking: "확인 중", unlimited: "무제한", serverLimit: "최대 {count}개", paidUntil: "결제 기간: {date}까지", cancellation: "기간 종료 시 해지 예약됨 · 결제 기간까지 혜택을 사용할 수 있습니다", stateChecking: "멤버십 자격 확인 중", refresh: "멤버십 상태 새로고침", freePrice: "¥0 / 월", productionPending: "정식 신청 준비 중", unlimitedCaveat: "‘무제한’은 등록 가능한 서버 수를 뜻합니다. 이 PC의 성능을 초과하는 동시 실행을 보장하지 않습니다.", previewHeading: "새 기능 미리 체험", previewOptIn: "준비가 끝난 미리 체험 기능에 선택적으로 참여", noPreviews: "현재 제공 중인 미리 체험 기능이 없습니다. 매월 추가를 약속하지 않습니다.", previewItem: "개발 중: {audience} / {impact}", themeHeading: "서포터 전용 테마", themeIntro: "기존 다크/라이트 테마와 강조 색상은 계속 무료입니다. 누구나 테마를 미리 볼 수 있습니다.", themeApplied: "적용됨", applyTheme: "테마 적용", supporterOnly: "서포터 전용", resetTheme: "기본 테마로 복원", themeResetNote: "자격이 끝나거나 로그아웃하면 기본 테마로 돌아갑니다. Windows 제목 표시줄은 변경되지 않습니다.", saved: "설정을 저장했습니다", failed: "설정을 저장하지 못했습니다. 연결을 확인하고 다시 시도하세요.", refreshFailed: "멤버십 새로고침에 실패했습니다. 기존 서버는 계속 사용할 수 있습니다.",
    themeDescriptions: { midnight: "깊은 파랑과 맑은 아쿠아", orchid: "차분한 보라와 부드러운 라일락", ember: "숯빛과 따뜻한 호박색" },
    states: { signed_out: "로그인되지 않음", session_expired: "로그인 세션이 만료되었습니다", not_configured: "멤버십 연결 준비 중", free: "무료 플랜", verified: "멤버십 자격 확인됨", offline: "오프라인 자격 사용 중(최대 24시간, 결제 기간 내)", unavailable: "연결에 실패했고 유효한 오프라인 자격이 없습니다", expired: "멤버십 자격이 만료되었습니다", past_due: "결제 확인이 필요합니다(무료 기능은 계속 사용 가능)", unpaid: "결제가 완료되지 않았습니다(무료 기능은 계속 사용 가능)", canceled: "구독이 종료되었습니다", invalid_qualification: "멤버십 서명을 확인할 수 없습니다", clock_invalid: "기기의 시각을 확인하세요", browser_demo: "브라우저 화면 데모", unknown: "멤버십 자격 확인 중" },
  },
  es: {
    kicker: "APOYO", freePlan: "Plan gratuito", supporterPlan: "Supporter", registeredCount: "Servidores registrados: {count}", countChecking: "comprobando", unlimited: "sin límite", serverLimit: "hasta {count}", paidUntil: "Pagado hasta {date}", cancellation: "Cancelación programada al final del periodo; las ventajas siguen hasta entonces", stateChecking: "Comprobando la suscripción", refresh: "Actualizar estado de la suscripción", freePrice: "¥0 / mes", productionPending: "La inscripción se está preparando", unlimitedCaveat: "«Sin límite» se refiere a servidores registrados; no garantiza que este PC pueda ejecutarlos todos a la vez.", previewHeading: "Acceso anticipado", previewOptIn: "Participar voluntariamente cuando las novedades estén listas", noPreviews: "No hay novedades disponibles ahora. No se garantizan nuevas funciones cada mes.", previewItem: "En desarrollo: {audience} / {impact}", themeHeading: "Temas para Supporter", themeIntro: "Los temas oscuro y claro y los colores de acento existentes siguen siendo gratuitos. Cualquiera puede verlos.", themeApplied: "Aplicado", applyTheme: "Aplicar tema", supporterOnly: "Solo Supporter", resetTheme: "Restaurar tema estándar", themeResetNote: "Al terminar la suscripción o cerrar sesión se restaura el tema estándar. No afecta a la barra de título de Windows.", saved: "Ajustes guardados", failed: "No se pudo guardar. Comprueba la conexión e inténtalo de nuevo.", refreshFailed: "No se pudo actualizar la suscripción. Los servidores existentes siguen disponibles.",
    themeDescriptions: { midnight: "Azul profundo y aguamarina clara", orchid: "Violeta sereno y lila suave", ember: "Carbón y ámbar cálido" },
    states: { signed_out: "Sesión no iniciada", session_expired: "La sesión ha caducado", not_configured: "Conexión de suscripción en preparación", free: "Plan gratuito", verified: "Suscripción verificada", offline: "Usando validación sin conexión (hasta 24 horas y dentro del periodo pagado)", unavailable: "Error de conexión y sin validación sin conexión válida", expired: "La suscripción ha caducado", past_due: "Hay que revisar el pago (las funciones gratuitas siguen disponibles)", unpaid: "Pago incompleto (las funciones gratuitas siguen disponibles)", canceled: "La suscripción terminó", invalid_qualification: "No se pudo verificar la firma de la suscripción", clock_invalid: "Comprueba el reloj del dispositivo", browser_demo: "Demostración visual del navegador", unknown: "Comprobando la suscripción" },
  },
  de: {
    kicker: "UNTERSTÜTZEN", freePlan: "Kostenloser Tarif", supporterPlan: "Supporter", registeredCount: "Registrierte Server: {count}", countChecking: "wird geprüft", unlimited: "unbegrenzt", serverLimit: "bis zu {count}", paidUntil: "Bezahlt bis {date}", cancellation: "Kündigung zum Periodenende vorgemerkt; Vorteile gelten bis dahin", stateChecking: "Mitgliedschaft wird geprüft", refresh: "Mitgliedschaft aktualisieren", freePrice: "¥0 / Monat", productionPending: "Anmeldung wird vorbereitet", unlimitedCaveat: "„Unbegrenzt“ bezieht sich auf registrierte Server und garantiert nicht, dass dieser PC alle gleichzeitig ausführen kann.", previewHeading: "Früher Zugriff", previewOptIn: "Freiwillig teilnehmen, sobald Vorschauen bereit sind", noPreviews: "Derzeit sind keine Vorschauen verfügbar. Monatliche Ergänzungen sind nicht garantiert.", previewItem: "In Entwicklung: {audience} / {impact}", themeHeading: "Supporter-Designs", themeIntro: "Die vorhandenen hellen und dunklen Designs sowie Akzentfarben bleiben kostenlos. Alle können sie ansehen.", themeApplied: "Aktiv", applyTheme: "Design anwenden", supporterOnly: "Nur für Supporter", resetTheme: "Standarddesign wiederherstellen", themeResetNote: "Nach Ablauf der Berechtigung oder Abmeldung wird das Standarddesign wiederhergestellt. Windows-Titelleisten bleiben unverändert.", saved: "Einstellungen gespeichert", failed: "Einstellung konnte nicht gespeichert werden. Prüfe die Verbindung und versuche es erneut.", refreshFailed: "Mitgliedschaft konnte nicht aktualisiert werden. Vorhandene Server bleiben verfügbar.",
    themeDescriptions: { midnight: "Tiefes Blau und klares Aquamarin", orchid: "Ruhiges Violett und sanftes Flieder", ember: "Kohle und warmes Bernstein" },
    states: { signed_out: "Nicht angemeldet", session_expired: "Anmeldesitzung abgelaufen", not_configured: "Mitgliedschaftsverbindung wird vorbereitet", free: "Kostenloser Tarif", verified: "Mitgliedschaft bestätigt", offline: "Offline-Berechtigung aktiv (bis zu 24 Stunden und innerhalb des bezahlten Zeitraums)", unavailable: "Verbindung fehlgeschlagen; keine gültige Offline-Berechtigung verfügbar", expired: "Mitgliedschaft abgelaufen", past_due: "Zahlung muss geprüft werden (kostenlose Funktionen bleiben verfügbar)", unpaid: "Zahlung ausstehend (kostenlose Funktionen bleiben verfügbar)", canceled: "Abonnement beendet", invalid_qualification: "Mitgliedschaftssignatur konnte nicht geprüft werden", clock_invalid: "Geräteuhr prüfen", browser_demo: "Browser-Demoansicht", unknown: "Mitgliedschaft wird geprüft" },
  },
  fr: {
    kicker: "SOUTIEN", freePlan: "Offre gratuite", supporterPlan: "Supporter", registeredCount: "Serveurs enregistrés : {count}", countChecking: "vérification", unlimited: "illimité", serverLimit: "jusqu’à {count}", paidUntil: "Payé jusqu’au {date}", cancellation: "Résiliation prévue en fin de période ; les avantages restent actifs jusque-là", stateChecking: "Vérification de l’abonnement", refresh: "Actualiser l’abonnement", freePrice: "¥0 / mois", productionPending: "Les inscriptions sont en préparation", unlimitedCaveat: "« Illimité » concerne les serveurs enregistrés, pas leur exécution simultanée au-delà des capacités de ce PC.", previewHeading: "Accès anticipé", previewOptIn: "Participer volontairement lorsque les aperçus seront prêts", noPreviews: "Aucun aperçu n’est disponible actuellement. Des ajouts mensuels ne sont pas garantis.", previewItem: "En développement : {audience} / {impact}", themeHeading: "Thèmes Supporter", themeIntro: "Les thèmes clair et sombre existants ainsi que les couleurs d’accent restent gratuits. Tout le monde peut les prévisualiser.", themeApplied: "Appliqué", applyTheme: "Appliquer le thème", supporterOnly: "Supporter uniquement", resetTheme: "Restaurer le thème standard", themeResetNote: "À l’expiration de l’éligibilité ou à la déconnexion, le thème standard est rétabli. La barre de titre Windows n’est pas concernée.", saved: "Paramètres enregistrés", failed: "Impossible d’enregistrer. Vérifiez la connexion puis réessayez.", refreshFailed: "Impossible d’actualiser l’abonnement. Les serveurs existants restent disponibles.",
    themeDescriptions: { midnight: "Bleu profond et aqua limpide", orchid: "Violet calme et lilas doux", ember: "Charbon et ambre chaleureux" },
    states: { signed_out: "Non connecté", session_expired: "La session a expiré", not_configured: "Connexion d’abonnement en préparation", free: "Offre gratuite", verified: "Abonnement vérifié", offline: "Éligibilité hors ligne (24 heures maximum et pendant la période payée)", unavailable: "Connexion échouée, aucune éligibilité hors ligne valide", expired: "Éligibilité expirée", past_due: "Paiement à vérifier (les fonctions gratuites restent accessibles)", unpaid: "Paiement incomplet (les fonctions gratuites restent accessibles)", canceled: "Abonnement terminé", invalid_qualification: "Signature d’abonnement invérifiable", clock_invalid: "Vérifiez l’horloge de l’appareil", browser_demo: "Démonstration d’interface dans le navigateur", unknown: "Vérification de l’abonnement" },
  },
  "pt-BR": {
    kicker: "APOIO", freePlan: "Plano gratuito", supporterPlan: "Supporter", registeredCount: "Servidores registrados: {count}", countChecking: "verificando", unlimited: "ilimitado", serverLimit: "até {count}", paidUntil: "Pago até {date}", cancellation: "Cancelamento agendado para o fim do período; benefícios seguem ativos até lá", stateChecking: "Verificando a assinatura", refresh: "Atualizar status da assinatura", freePrice: "¥0 / mês", productionPending: "A adesão está sendo preparada", unlimitedCaveat: "“Ilimitado” se refere aos servidores registrados; não garante que este PC possa executar todos ao mesmo tempo.", previewHeading: "Acesso antecipado", previewOptIn: "Participar voluntariamente quando as novidades estiverem prontas", noPreviews: "Não há prévias disponíveis no momento. Adições mensais não são garantidas.", previewItem: "Em desenvolvimento: {audience} / {impact}", themeHeading: "Temas Supporter", themeIntro: "Os temas claro e escuro existentes e as cores de destaque continuam gratuitos. Todos podem visualizar estes temas.", themeApplied: "Aplicado", applyTheme: "Aplicar tema", supporterOnly: "Exclusivo para Supporter", resetTheme: "Restaurar tema padrão", themeResetNote: "Quando a qualificação terminar ou você sair da conta, o tema padrão será restaurado. A barra de título do Windows não é afetada.", saved: "Configurações salvas", failed: "Não foi possível salvar. Confira a conexão e tente novamente.", refreshFailed: "Não foi possível atualizar a assinatura. Os servidores existentes continuam disponíveis.",
    themeDescriptions: { midnight: "Azul profundo e água-marinha clara", orchid: "Violeta sereno e lilás suave", ember: "Carvão e âmbar quente" },
    states: { signed_out: "Não conectado", session_expired: "A sessão expirou", not_configured: "Conexão da assinatura em preparação", free: "Plano gratuito", verified: "Assinatura verificada", offline: "Qualificação offline (até 24 horas e durante o período pago)", unavailable: "Falha de conexão e nenhuma qualificação offline válida", expired: "A qualificação expirou", past_due: "O pagamento precisa de atenção (recursos gratuitos continuam disponíveis)", unpaid: "Pagamento incompleto (recursos gratuitos continuam disponíveis)", canceled: "Assinatura encerrada", invalid_qualification: "Não foi possível verificar a assinatura", clock_invalid: "Confira o relógio do dispositivo", browser_demo: "Demonstração visual no navegador", unknown: "Verificando a assinatura" },
  },
};

export type SupporterPanelMessageKey = Exclude<keyof PanelMessages, "themeDescriptions" | "states">;
export function supporterPanelText(locale: AppLocale, key: SupporterPanelMessageKey, values: Record<string, string> = {}) {
  const message = copies[locale][key] as string;
  return Object.entries(values).reduce((result, [name, replacement]) => result.replaceAll("{" + name + "}", replacement), message);
}
export function supporterMembershipState(locale: AppLocale, state: string) {
  return copies[locale].states[state as StateKey] ?? copies[locale].states.unknown;
}
export function supporterThemeDescription(locale: AppLocale, theme: keyof typeof en.themeDescriptions) {
  return copies[locale].themeDescriptions[theme];
}
export function allSupporterPanelLocalesHaveCompleteMessages() {
  const keys = Object.keys(en).sort().join("|");
  const states = Object.keys(en.states).sort().join("|");
  return Object.values(copies).every((copy) => Object.keys(copy).sort().join("|") === keys
    && Object.keys(copy.states).sort().join("|") === states
    && Object.keys(copy.themeDescriptions).sort().join("|") === Object.keys(en.themeDescriptions).sort().join("|")
    && Object.values(copy.states).every(Boolean));
}
